<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/01_creating_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#CREATING NUMPY ARRAY
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# 2D AND 3D NUMPY ARRAY
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c= np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [9]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [10]:
np.array([4,5,6],dtype=str)

array(['4', '5', '6'], dtype='<U1')

In [12]:
# np.arange()
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# with reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
# np.ones np.zeros
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#np.random()
np.random.random((3,3))

array([[0.22831866, 0.40985087, 0.27563295],
       [0.67898387, 0.5279595 , 0.18301426],
       [0.66706685, 0.98870689, 0.18398145]])

In [25]:
#np.linspace
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])