<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/02_numpy_array_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY** **ATTRIBUTES**

In [21]:
import numpy as np

a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
#ndim
a1.ndim
a2.ndim
a3.ndim

3

In [11]:
#shape
print(a1.shape)
a1

print(a2.shape)
a2

print(a3.shape)
a3

(10,)
(3, 4)
(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
#size
print(a1.size)
print(a1)

print(a2.size)
print(a2)

print(a3.size)
print(a3)

10
[0 1 2 3 4 5 6 7 8 9]
12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [19]:
#itemsize -- tells every item is consuming how much space in memory
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [22]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64
