<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/03_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY** **OPERATIONS**

In [2]:
import numpy as np


In [6]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(" ")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [9]:
#Arithmetic operations
print(a1+2)
print(" ")
print(a1*2)
print(" ")
print(a1%2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
 
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
 
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [12]:
#relational operations
print(a1>15)

print(" ")

print(a1==53)

print(" ")

print(a1!=24)

[[False False False False]
 [False False False False]
 [False False False False]]
 
[[False False False False]
 [False False False False]
 [False False False False]]
 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [23]:
#Aggregate operations

print(np.sum(a1))

print(" ")

print(np.min(a1))
print(np.max(a1))
print(np.mean(a1))
print(np.median(a1))
print(np.var(a1))
print(np.exp(a1))

66
 
0
11
5.5
5.5
11.916666666666666
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [27]:
#Searching

print(np.argmax(a2))

print(np.argmin(a2))


11
0


In [16]:
#vector arithmetic operations

print (a1+a2)

print(" ")

print(a1*a2)

print(" ")

print(a1-a2)

print(" ")

print(a1**a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
 
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
 
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
 
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]
