<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/04_array_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY** **FUNCTIONS**

In [53]:
import numpy as np

In [54]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)

[[ 5. 59. 50.]
 [74. 49. 44.]
 [77. 22. 41.]]


In [55]:
print(np.max(a1))

print(np.min(a1))

print(np.sum(a1))

print(np.prod(a1))

print(np.max(a1,axis=1)) # row

print(np.max(a1,axis=0)) #column

print(np.sum(a1,axis=0))

print(np.prod(a1,axis=1))

print(np.sum(a1,axis=0))

print(" ")
print(np.mean(a1))
print(np.mean(a1,axis=1))
print(np.mean(a1,axis=0))

77.0
5.0
421.0
163444292396000.0
[59. 74. 77.]
[77. 59. 50.]
[156. 130. 135.]
[ 14750. 159544.  69454.]
[156. 130. 135.]
 
46.77777777777778
[38.         55.66666667 46.66666667]
[52.         43.33333333 45.        ]


In [56]:
print(np.sin(a1))

print(" ")

print(np.tan(a1))


[[-0.95892427  0.63673801 -0.26237485]
 [-0.98514626 -0.95375265  0.01770193]
 [ 0.99952016 -0.00885131 -0.15862267]]
 
[[-3.38051501e+00 -8.25774009e-01 -2.71900612e-01]
 [-5.73702254e+00 -3.17290855e+00  1.77046993e-02]
 [-3.22685758e+01  8.85165604e-03  1.60656699e-01]]


In [57]:
#DOT PRODUCT,log
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(4,3)
print(a3)
print(" ")
print(a4)

print(" ")

print(np.dot(a3,a4))

print(" ")

print(np.log(a1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
 
[[114 120 126]
 [378 400 422]
 [642 680 718]]
 
[[1.60943791 4.07753744 3.91202301]
 [4.30406509 3.8918203  3.78418963]
 [4.34380542 3.09104245 3.71357207]]


**INDEXING** **AND** **SLICING**

In [58]:
m1=np.arange(12)
m2=np.arange(12).reshape((3,4))
m3=np.arange(8).reshape(2,2,2)
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
print(m2[1,2])
print(m2[2,3])

6
11


In [60]:
print(m3)

print(" ")

print(m3[1,0,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
 
5


In [63]:
#SLICING
print(m2)

print(" ")

print(m2[0,:])
print(m2[2,:])
print(m2[:,2])

print(" ")
print(m2[1:,1:3])

print(" ")
print(m2[0:,1:])

print(" ")
print(m2[::2,::3])

print(" ")
print(m2[0::2,1::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[0 1 2 3]
[ 8  9 10 11]
[ 2  6 10]
 
[[ 5  6]
 [ 9 10]]
 
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
 
[[ 0  3]
 [ 8 11]]
 
[[ 1  3]
 [ 9 11]]


In [69]:
m3=np.arange(27).reshape(3,3,3)
print(m3)
print(" ")
print(m3[1])

print(" ")
print(m3[0,1,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
 
[3 4 5]


**IRERATING**

In [73]:
print(m1)

for i in m1:
  print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [74]:
print(m2)

for i in m2:
  print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [77]:
print(m3)
print(" ")
for i in m3:
  print(i)

  print(" ")

for i in np.nditer(m3):
  print(i)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
 
[[18 19 20]
 [21 22 23]
 [24 25 26]]
 
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [78]:
m3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [79]:
m2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [80]:
np.transpose(m2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

**STACKING**

In [82]:
#HORIZONTAL STACKING
l1=np.arange(12).reshape(3,4)
l2=np.arange(12,24).reshape(3,4)

print(np.hstack((l1,l2)))

print(" ")

print(np.vstack((l1,l2)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
