<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/05_numpy_arrays_vs_python_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY** **ARRAY** **VS** **PYTHON** **LIST**

In [ ]:
#ON BASIS OF TIME

In [1]:
#python list
import time
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]

start=time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

3.3430116176605225


In [2]:
#numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.18765473365783691


In [ ]:
# ON BASIS OF MEMORY

In [3]:
import sys
a=[i for i in range(10000000)]
sys.getsizeof(a)

89095160

In [6]:
a1=np.arange(10000000,dtype=np.int16)
sys.getsizeof(a1)

20000112

**ADVANCED** **INDEXING**

In [13]:
a=np.arange(24).reshape(6,4)
print(a)

print(" ")


#fancy indexing it is used when we are not able to find patterns

print(a[[0,3,4,5]])  #rowwise

print(" ")

print(a[:,[0,2,3]])  #columnwise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
 
[[ 0  1  2  3]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
 
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [29]:
#boolean indexing
a2=np.random.randint(1,100,24).reshape(6,4)
print(a2)


#find all the numbeer greater than 50
print(" ")
print(a2>50)

print(" ")
print(a2[a2>50])

print(" ")
print(a2[a2%2==0])

print(" ")
print(a2[(a2>50) & (a2%2==0)])

[[20 86 95 92]
 [40 81 13 40]
 [68 33 98 44]
 [70 52 88 44]
 [51 44 76 11]
 [24 67 55 19]]
 
[[False  True  True  True]
 [False  True False False]
 [ True False  True False]
 [ True  True  True False]
 [ True False  True False]
 [False  True  True False]]
 
[86 95 92 81 68 98 70 52 88 51 76 67 55]
 
[20 86 92 40 40 68 98 44 70 52 88 44 44 76 24]
 
[86 92 68 98 70 52 88 76]
