<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/06_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**BROADCASTING**

In [4]:
#same shape
import numpy as np

a1=np.arange(6).reshape(2,3)
a2=np.arange(6,12).reshape(2,3)

print(a1)
print(" ")
print(a2)
print(" ")
print(a1+a2)


print(" ")

a3=np.arange(3).reshape(1,3)
print(a1+a3)

[[0 1 2]
 [3 4 5]]
 
[[ 6  7  8]
 [ 9 10 11]]
 
[[ 6  8 10]
 [12 14 16]]
 
[[0 2 4]
 [3 5 7]]
