<a href="https://colab.research.google.com/github/architawasthi99/numpy/blob/main/08_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**SORTING**

In [ ]:
# np.sort

a1=np.random.randint(1,100,15)
print(a1)

print(np.sort(a1))
print(np.sort(a1)[::-1])

[50 12 45 34 33 42 64 48 23 12 93 75 72 92 92]
[12 12 23 33 34 42 45 48 50 64 72 75 92 92 93]
[93 92 92 75 72 64 50 48 45 42 34 33 23 12 12]


In [ ]:
a2=np.random.randint(1,100,16).reshape(4,4)
print(a2)

print(" ")
print(np.sort(a2))

print(" ")
print(np.sort(a2,axis=0))  #column wise

print(" ")
print(np.sort(a2,axis=0)[::-1])

[[61 78 87 28]
 [57  8 69 59]
 [91 61 10 87]
 [52 11  9 66]]
 
[[28 61 78 87]
 [ 8 57 59 69]
 [10 61 87 91]
 [ 9 11 52 66]]
 
[[52  8  9 28]
 [57 11 10 59]
 [61 61 69 66]
 [91 78 87 87]]
 
[[91 78 87 87]
 [61 61 69 66]
 [57 11 10 59]
 [52  8  9 28]]


**APPEND**

In [ ]:
#np.append()
np.append(a1,1)

array([50, 12, 45, 34, 33, 42, 64, 48, 23, 12, 93, 75, 72, 92, 92,  1])

In [ ]:
np.append(a2,2)

array([61, 78, 87, 28, 57,  8, 69, 59, 91, 61, 10, 87, 52, 11,  9, 66,  2])

In [ ]:
np.append(a2,np.ones((a2.shape[0],1)),axis=1)

array([[61., 78., 87., 28.,  1.],
       [57.,  8., 69., 59.,  1.],
       [91., 61., 10., 87.,  1.],
       [52., 11.,  9., 66.,  1.]])

In [ ]:
#np.column_stack()

arr1=np.arange(6).reshape(3,2)
arr2=np.array([10,20,30])

result=np.column_stack((arr1,arr2))
print(result)

[[ 0  1 10]
 [ 2  3 20]
 [ 4  5 30]]


**CONCATINATE**

In [ ]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

print(np.concatenate((a,b),axis=0))

print(" ")

print(np.concatenate((a,b),axis=1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
 
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [ ]:
#np.unique

a=np.array([1,1,2,3,3,3,4,4,5,5,5,5,5,5,55])
np.unique(a)

array([ 1,  2,  3,  4,  5, 55])

In [ ]:
#np.expand_dims {used to inc dimentions of the array}
a=np.arange(6)

print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=0).shape)

print(" ")

print(np.expand_dims(a,axis=1))
print(np.expand_dims(a,axis=1).shape)

[[0 1 2 3 4 5]]
(1, 6)
 
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [ ]:
#np.where(condition,true,false)
#returns the indices of the elements which satisfy the given condition

a1

array([50, 12, 45, 34, 33, 42, 64, 48, 23, 12, 93, 75, 72, 92, 92])

In [ ]:
print(np.where(a1>50)) #gives index
print(a1[np.where(a1>50)]) #gives values of that index

#replace all the values above 50 with 0
print(" ")
print(np.where(a1>50,0,a1))


print(" ")
print(np.where(a1%2==0,2,a1))

(array([ 6, 10, 11, 12, 13, 14]),)
[64 93 75 72 92 92]
 
[50 12 45 34 33 42  0 48 23 12  0  0  0  0  0]
 
[ 2  2 45  2 33  2  2  2 23  2 93 75  2  2  2]


In [ ]:
#np.argmax()
a1

array([50, 12, 45, 34, 33, 42, 64, 48, 23, 12, 93, 75, 72, 92, 92])

In [ ]:
print(a1.argmax())
print(a1[a1.argmax()])

10
93


In [1]:
#np.cumssum()

import numpy as np
z=np.arange(15)
print(z)

print(np.cumsum(z))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105]


In [4]:
#np.cumprod   cumulative product

arr=np.arange(1,10)
np.cumprod(arr)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [7]:
#  np.percentile
print(arr)
print(np.percentile(arr,100))
print(np.percentile(arr,0))

[1 2 3 4 5 6 7 8 9]
9.0
1.0


In [10]:
#np.histogram()
arr=np.arange(1,101)
np.histogram(arr,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([ 9, 10, 10, 10, 10, 10, 10, 10, 10, 11]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [11]:
#np.corrcoef
#correlation coefficients

salary=np.array([10000,20000,30000,40000,50000])
exp=np.array([1,2,1,3,4])
np.corrcoef(salary,exp)

array([[1.        , 0.84887469],
       [0.84887469, 1.        ]])

In [14]:
#np.isin()
arr=np.arange(21,78)
items=[10,20,30,40]
arr[np.isin(arr,items)]

array([30, 40])

In [17]:
#np.put used to update multiple values at once
print(arr)
np.put(arr,[0,1,2],[11,12,13])
print(" ")
print(arr)

[11 12 13 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77]
 
[11 12 13 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77]
